In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("adirizq/shopee-product-images")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/adirizq/shopee-product-images?dataset_version_number=2...

100%|██████████| 5.14G/5.14G [00:50<00:00, 110MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/adirizq/shopee-product-images/versions/2

In [ ]:
import os


path = "/root/.cache/kagglehub/datasets/adirizq/shopee-product-images/versions/2"


for item in os.listdir(path):
    print(item)

data_products_id_small.csv
images
data_products_id_tiny.csv

In [ ]:
import pandas as pd

# Caminho do dataset
path = "/root/.cache/kagglehub/datasets/adirizq/shopee-product-images/versions/2"

# Caminho completo para o CSV
csv_file = os.path.join(path, "data_products_id_small.csv")

df = pd.read_csv(csv_file)

print("Colunas:", df.columns)

df.head()

Colunas: Index(['product_id', 'image', 'name', 'shop_name', 'shopid', 'main_category',
       'sub_category'],
      dtype='object')

,product_id,image,name,shop_name,shopid,main_category,sub_category
0,12523520280,e6205d4fcb8a485235778ad210ac4d90,PS3 Super Slim 1TB Full Game + 2 Stik getar + ...,spirit elektronik,379815570,Elektronik,Konsol Game
1,17941082335,8563c9fc31b880ed105f91b8d43e6d88,GAMEBOY PVP DUAL ANALOG FULLSET BISA MAIN DI T...,Gaming Console Store,268909000,Elektronik,Konsol Game
2,23517487660,id-11134207-7qul7-leyb85rn449s74,Pulsa Min A10 K1T Remote,GAMOLBERKAH,102394348,Elektronik,Konsol Game
3,7978948479,d6b77df3df58d6a13b3d78eeb303cbb5,DUS PSP-2004/ DUS PSP STREET E1004,GAMES168,28318233,Elektronik,Konsol Game
4,4653307963,f888e78a3845120009602a0b23e65ce0,playstation 2 full game|| hardis external full...,Milkha_shop,293187724,Elektronik,Konsol Game

In [ ]:
import pandas as pd

# Caminho do dataset
path = "/root/.cache/kagglehub/datasets/adirizq/shopee-product-images/versions/2"

# Caminho completo para o CSV
csv_file = os.path.join(path, "data_products_id_tiny.csv")
df = pd.read_csv(csv_file)
print("Colunas:", df.columns)
df.head()

Colunas: Index(['product_id', 'image', 'name', 'shop_name', 'shopid', 'main_category',
       'sub_category'],
      dtype='object')

,product_id,image,name,shop_name,shopid,main_category,sub_category
0,19941741813,9cedf3c19821e83aa88a1e2f401e4e3b,Plac Poles sepatu Bersih Cream Pemutih Shoes S...,rejeki007,519630646,Sepatu Pria,Aksesoris & Perawatan Sepatu
1,8609667001,94b8c7d8fabca08490e1398864a7e3d7,Bantalan Sepatu Depan / Insole (2pcs) - PR0015,Neofelis Houseware,113260191,Sepatu Wanita,Aksesoris & Perawatan Sepatu
2,845133903,882bfbef267af16d4a84624d1f33a885,MKL - Saddle Shoes / Shoee Tree Catokan Sepatu...,jakartakinesio,1317599,Sepatu Pria,Aksesoris & Perawatan Sepatu
3,11448295634,2d16dcd0429f2c198fd3381d17696d5b,"ANTI JAMUR TAS KULIT DAUN TALAS ANTI AIR, LEAT...",Garael Official Store,526900249,Sepatu Pria,Aksesoris & Perawatan Sepatu
4,12648185204,25eac0de61c8e0f0821daf72fb37f8c6,1 Pasang Insole Pad dan T-Shape Untuk Sepatu H...,Dishdash,14226667,Sepatu Wanita,Aksesoris & Perawatan Sepatu